name: CI
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Install Pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "7.x"
      # Cache node_modules
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      # Install workspace dependencies
      - name: Install dependencies
        run: pnpm install

      # Install fly.io cly
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - uses: nrwl/nx-set-shas@v4

      # # This line is needed for nx affected to work when CI is running on a PR
      # - run: git branch --track main origin/main

      # - run: pnpm dlx nx format:check
      - run: pnpm dlx nx affected -t deploy # TODO: add linter, tests
